function StdAtm_01000km = importStdAtm(filename, dataLines)
%IMPORTFILE Import data from a text file
%  STDATM01000KM = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  STDATM01000KM = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  StdAtm01000km = importfile("/Users/xyz/Desktop/StdAtm_0_1000km.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Dec-2024 14:32:56

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Z", "H", "T", "TT0", "p", "pp0", "rho", "rhorho0", "c", "g"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
StdAtm_01000km = readtable(filename, opts);

end