function stdatmtransport = import_transport(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  STDATMTRANSPORT = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  STDATMTRANSPORT = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  STDATMTRANSPORT = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  stdatmtransport = importfile("/Users/xyz/Desktop/std_atm_transport.xlsx", "Sheet1", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Dec-2024 15:22:11

%% Input handling

% If no sheet is specified, read from Sheet1
if nargin == 1 || isempty(sheetName)
    sheetName = "Sheet1";
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 11);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["htact", "htgeo", "dynvisc", "kinvisc", "prsclht", "numdens", "partspd", "colfreq", "mfp", "thermcond", "molweight"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
stdatmtransport = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    stdatmtransport = [stdatmtransport; tb]; %#ok<AGROW>
end

end